<?php

namespace App\Enums;

enum PermissionType: string
{
    // Category
    case VIEW_ALL_CATEGORIES = 'VIEW_ALL_CATEGORIES';
    case RESTORE_CATEGORIES = 'RESTORE_CATEGORIES';
    case CREATE_CATEGORIES = 'CREATE_CATEGORIES';
    case MOVE_CATEGORIES = 'MOVE_CATEGORIES';
    case UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
    case DELETE_CATEGORIES = 'DELETE_CATEGORIES';

    // Statistical
    case VIEW_STATISTICAL = 'VIEW_STATISTICAL';

    // Product
    case VIEW_PRODUCTS_ADMIN = 'VIEW_PRODUCTS_ADMIN';
    case CREATE_PRODUCT = 'CREATE_PRODUCT';
    case UPDATE_PRODUCT = 'UPDATE_PRODUCT';
    case RESTORE_PRODUCT = 'RESTORE_PRODUCT';
    case DELETE_PRODUCT = 'DELETE_PRODUCT';

    // User
    case VIEW_USERS = 'VIEW_USERS';
    case VIEW_USER_DETAIL = 'VIEW_USER_DETAIL';
    case CREATE_USER = 'CREATE_USER';
    case ASSIGN_ROLE = 'ASSIGN_ROLE';
    case VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';

    // Order
    case VIEW_ORDERS_ADMIN = 'VIEW_ORDERS_ADMIN';
    case UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';

    // Supplier
    case ADD_SUPPLIER = 'ADD_SUPPLIER';

    // HRM: Schedules
    case VIEW_SCHEDULE_REPORT = 'VIEW_SCHEDULE_REPORT';
    case VIEW_DAILY_SCHEDULE = 'VIEW_DAILY_SCHEDULE';
    case SET_DEFAULT_SCHEDULE = 'SET_DEFAULT_SCHEDULE';
    case ASSIGN_SHIFT = 'ASSIGN_SHIFT';
    case DELETE_SHIFT_ASSIGNMENT = 'DELETE_SHIFT_ASSIGNMENT';

    // HRM: Leave Requests
    case VIEW_LEAVE_LIST = 'VIEW_LEAVE_LIST';
    case APPROVE_LEAVE = 'APPROVE_LEAVE';

    // HRM: Shifts & Holidays
    case CREATE_SHIFT = 'CREATE_SHIFT';
    case UPDATE_SHIFT = 'UPDATE_SHIFT';
    case DELETE_SHIFT = 'DELETE_SHIFT';
    case MANAGE_HOLIDAYS = 'MANAGE_HOLIDAYS';

    // HRM: Career & Position
    case PROMOTE_EMPLOYEE = 'PROMOTE_EMPLOYEE';
    case CREATE_POSITION = 'CREATE_POSITION';
    case UPDATE_POSITION = 'UPDATE_POSITION';
    case DELETE_POSITION = 'DELETE_POSITION';

    // Salary
    case CREATE_SALARY_CONFIG = 'CREATE_SALARY_CONFIG';
    case UPDATE_SALARY_CONFIG = 'UPDATE_SALARY_CONFIG';
    case DELETE_SALARY_CONFIG = 'DELETE_SALARY_CONFIG';
    case MANAGE_SALARY_SCALES = 'MANAGE_SALARY_SCALES';
    case CALCULATE_SALARY = 'CALCULATE_SALARY';

    // RBAC & System
    case MANAGE_ROLES = 'MANAGE_ROLES';
    case MANAGE_PERMISSION_GROUPS = 'MANAGE_PERMISSION_GROUPS';
    case EXPORT_DATA = 'EXPORT_DATA';
}