<?php

namespace App\Enums;

enum PermissionType: string
{
    case VIEW_ALL_CATEGORIES = 'VIEW_ALL_CATEGORIES';
    case RESTORE_CATEGORIES = 'RESTORE_CATEGORIES';
    case CREATE_CATEGORIES = 'CREATE_CATEGORIES';
    case MOVE_CATEGORIES = 'MOVE_CATEGORIES';
    case UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
    case DELETE_CATEGORIES = 'DELETE_CATEGORIES';
    case VIEW_DETAIL_CATEGORIES = 'VIEW_DETAIL_CATEGORIES';

    case CREATE_ORDER_SHIP = 'CREATE_ORDER_SHIP';
    case CREATE_RETURN_ORDER_SHIP = 'CREATE_RETURN_ORDER_SHIP';

    case VIEW_ALL_ORDER = 'VIEW_ALL_ORDER';
    case CHANGE_STATUS_ORDER = 'CHANGE_STATUS_ORDER';
    case VIEW_DETAIL_ORDER = 'VIEW_DETAIL_ORDER';

    case VIEW_ALL_PRODUCT = 'VIEW_ALL_PRODUCT';
    case CREATE_PRODUCT = 'CREATE_PRODUCT';
    case UPDATE_PRODUCT = 'UPDATE_PRODUCT';
    case RESTORE_PRODUCT = 'RESTORE_PRODUCT';
    case DELETE_PRODUCT = 'DELETE_PRODUCT';
    case VIEW_DETAIL_PRODUCT = 'VIEW_DETAIL_PRODUCT';

    case ADD_PRODUCT_VARIANT = 'ADD_PRODUCT_VARIANT';
    case UPDATE_PRODUCT_VARIANT = 'UPDATE_PRODUCT_VARIANT';
    case DELETE_PRODUCT_VARIANT = 'DELETE_PRODUCT_VARIANT';

    case VIEW_ALL_USER = 'VIEW_ALL_USER';
    case CREATE_USER = 'CREATE_USER';
    case UPDATE_STATUS_USER = 'UPDATE_STATUS_USER';
    case VIEW_DETAIL_USER = 'VIEW_DETAIL_USER';

    case ADD_PRODUCT_ATTRIBUTE = 'ADD_PRODUCT_ATTRIBUTE';
    case UPDATE_PRODUCT_ATTRIBUTE = 'UPDATE_PRODUCT_ATTRIBUTE';
    case DELETE_PRODUCT_ATTRIBUTE = 'DELETE_PRODUCT_ATTRIBUTE';

    case ADD_PRODUCT_ATTRIBUTE_VALUE = 'ADD_PRODUCT_ATTRIBUTE_VALUE';
    case UPDATE_PRODUCT_ATTRIBUTE_VALUE = 'UPDATE_PRODUCT_ATTRIBUTE_VALUE';
    case DELETE_PRODUCT_ATTRIBUTE_VALUE = 'DELETE_PRODUCT_ATTRIBUTE_VALUE';
    case DELETE_PRODUCT_ATTRIBUTE_VALUE_IMAGE = 'DELETE_PRODUCT_ATTRIBUTE_VALUE_IMAGE';

    case ADD_IMAGE_PRODUCT = 'ADD_IMAGE_PRODUCT';
    case DELETE_IMAGE_PRODUCT = 'DELETE_IMAGE_PRODUCT';

    case VIEW_ALL_IMPORT_PRODUCT = 'VIEW_ALL_IMPORT_PRODUCT';
    case ADD_IMPORT_PRODUCT = 'ADD_IMPORT_PRODUCT';
    case VIEW_DETAIL_IMPORT_PRODUCT = 'VIEW_DETAIL_IMPORT_PRODUCT';
    case CONFIRM_IMPORT_PRODUCT = 'CONFIRM_IMPORT_PRODUCT';
    case CANCEL_IMPORT_PRODUCT = 'CANCEL_IMPORT_PRODUCT';
    case DELETE_IMPORT_PRODUCT_DETAIL = 'DELETE_IMPORT_PRODUCT_DETAIL';
    case UPDATE_QUANTITY_IMPORT_PRODUCT = 'UPDATE_QUANTITY_IMPORT_PRODUCT';

    case CHANGE_STATUS_RETURN_ORDER = 'CHANGE_STATUS_RETURN_ORDER';
    case VIEW_DETAIL_ROLE = 'VIEW_DETAIL_ROLE';
    case UPDATE_STATUS_ROLE = 'UPDATE_STATUS_ROLE';
    case VIEW_STATISTICAL = 'VIEW_STATISTICAL';
    case ADD_ROLE = 'ADD_ROLE';
    case DELETE_ROLE = 'DELETE_ROLE';
    case VIEW_ALL_RETURN_ORDER = 'VIEW_ALL_RETURN_ORDER';

    case ADD_SUPPLIER = 'ADD_SUPPLIER';
    case RESTORE_SUPPLIER = 'RESTORE_SUPPLIER';
    case UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
    case DELETE_SUPPLIER = 'DELETE_SUPPLIER';
    case VIEW_DETAIL_SUPPLIER = 'VIEW_DETAIL_SUPPLIER';

    case VIEW_ALL_USER_RANK = 'VIEW_ALL_USER_RANK';
    case ADD_USER_RANK = 'ADD_USER_RANK';
    case UPDATE_USER_RANK = 'UPDATE_USER_RANK';
    case DELETE_USER_RANK = 'DELETE_USER_RANK';
}
